import LocalizedStrings from 'react-localization';

const strings = new LocalizedStrings({
  'zh-Hans': {
    appName: 'WOOKONG钱包',
    language: '软件语言',
    closeModal: '关闭',
    closeMemoModal: '取消',
    memoSubmit: '完成',
    copyAddress: '复制地址',
    saveImg: '保存二维码',
    copyPbkey: '复制公钥',
    settings: '设置',
    reload: '刷新重连',
    unlockToast: '请检查设备状态，确保其已解锁',
    reconnectToast: '请重新连接设备',
    modifyPINError: '修改PIN出错，请检查并重试',
    modifyPINSuccess: '修改PIN成功，软件即将重启',
    sendTxSuccess: '发送交易成功：{0}。点击查看',
    sendTxError: '发送交易失败，请检查并稍后重试',
    confirmLaunchText: '请确认已插入所有之后要用到的<b>星钥</b>',
    confirmLaunchHint: '提示：插入单个星钥 可进入个人模式',
    astroKey: '星钥',
    confirmLaunchBtn: '确认并启动',
    connectError: '连接错误',
    connectHintNotSameGroup:
      '插入的星钥中有非同一组的星钥，请检查重试或联系官方技术支持',
    connectHintNotInited: '有星钥未初始化，请检查重试或联系官方技术支持',
    connectHintTooMuchDev: '插入设备过多，请每次只连接一个设备',
    connectSuccess: '连接成功',
    fetchingAddresses: '正在获取地址……',
    fetchingHint: '请在设备上按“OK”键以授权获取地址',
    readyToInit: '准备初始化',
    readyHint: '初始化后方可使用 <b>WOOKONG硬件钱包</b>',
    connecting: '连接硬件中……',
    connectingHint: '提示：请输入PIN以解锁设备',
    connectingHintNotReady:
      '设备状态错误，请确认设备处于解锁状态，屏幕上显示WOOKONG',
    retry: '重试',
    next: '下一步',
    createNewWallet: '创建钱包',
    importmemo: '导入助记词',
    importmemolabel: '输入助记词',
    importmemoTips: '请保证在设备解锁后再点击确定',
    importmemoIng: '正在导入助记词',
    importmemoIngTips: '请根据设备上的提示进行操作',
    importmemoSubmit: '确定',
    importmemoError: '导入助记词错误',
    importmemoErrorTips: '请确认输入内容无误再重试',
    importmemoSuccess: '导入成功',
    noKeys: '未检测到设备或插入了错误的设备',
    tooManyKeys: '插入的星钥个数超出限制',
    initError: '配置错误',
    retryHint: '请检查重试或联系官方技术支持',
    initSuccess: '配置成功',
    initSuccessHint: '提示：请输入PIN以解锁设备，并“确认”以授权获取地址',
    initing: '正在配置 <b>WOOKONG Enterprise</b>',
    initingHint: '请耐心等待配置完成 按设备上的提示备份助记词 请勿中途退出',
    checkAndRetry: '出错，检查并重试',
    enter: '进入钱包',
    selectThreshold: '请选择最少签名数',
    minThresholdHint: '<b>WOOKONG Enterprise</b>至少需要2份签名',
    keymanageMode: '星钥管理',
    modifyPINOption: '修改PIN',
    modifyPINOptionHint: '请根据设备上的提示进行操作',
    FingerprintOption: '管理指纹',
    FingerprintOptionHint: '查看已有指纹或添加删除指纹',
    DiskOption: '磁盘管理',
    DiskOptionHint: '使用密码打开磁盘或格式化磁盘',
    format: '格式化钱包',
    formatHint: '格式化后所有信息将被清除,请确保资产安全再进行此操作',
    formatError: '格式化失败',
    formatSuccess: '成功！软件即将重启',
    tabItemOverview: '概览',
    tabItemSend: '发送',
    tabItemProfile: '设置',
    address: '地址',
    copiedToClipboard: '已复制到系统剪贴板',
    checkAddressInfo: '地址详情',
    eosRegisterConfirmKey: '请对比硬件屏幕上显示的公钥，确保两者一致',
    confirmAddressOnKey:
      '请对比硬件屏幕上显示的地址，确保跟弹框上的一致。按“OK”确认地址以使用复制功能及显示二维码；按“C”以取消并关闭弹窗',
    confirmRegAddressOnKey:
      '请对比硬件屏幕上显示的公钥，确保两者一致。按“OK”以确认提交',
    confirmCopyAddressOnKey:
      '请对比硬件屏幕上显示的公钥，若一致，请按“OK”确认，并使用该公钥自行注册EOS账户；否则，按“C”取消。',
    waitConfirm: '等待确认',
    totalAssets: '总资产',
    balance: '余额',
    fee: '矿工费',
    fullBalance: '全部余额',
    advanced: '高级选项',
    alreadyUpdateMention: '已是最新版',
    updateMention: '发现新版本!',
    updateSpanSW: '软件',
    updateSpanFW: '固件',
    btcFeePolicyFasterLabel: '矿工费策略 速度/紧急',
    btcFeePolicyFasterText: '速度优先：紧急',
    btcFeePolicyFastLabel: '矿工费策略 速度/快',
    btcFeePolicyFastText: '速度优先：快',
    btcFeePolicyNormalLabel: '矿工费策略 正常',
    btcFeePolicyNormalText: '正常',
    btcFeePolicyEconomicalLabel: '矿工费策略 费用/经济',
    btcFeePolicyEconomicalText: '费用优先：经济',
    btcFeePolicyCheapLabel: '矿工费策略 费用/便宜',
    btcFeePolicyCheapText: '费用优先：便宜',
    btcFeePolicyPoorLabel: '矿工费策略 费用/极低',
    btcFeePolicyPoorText: '费用优先：极低',
    ethFeePolicyDefaultLabel: '矿工费策略 默认',
    ethFeePolicyDefaultText: '系统默认：自动计算',
    ethFeePolicyCustomLabel: '矿工费策略 自定义',
    ethFeePolicyCustomText: '高级选项：自定义',
    estimate: '预估',
    minute: '分钟',
    coinType: '币种',
    latestVersion: '当前已是最新版本',
    latestTotal: '软件和固件已是最新版本',
    setttingSW: '软件版本:',
    setttingFW: '固件版本:',
    latestCOSVersion: '当前固件已是最新版本',
    recipientAddress: '收款人地址',
    recipientHint: '请输入收款人地址',
    memo: '备注',
    memoHint: '转账备注（可选）',
    sendAmount: '转账金额',
    exceedBalanceHint: '转账金额+矿工费须小于余额',
    xrpBalanceNotEnough: '扣除转账金额+矿工费后最少须保留20 XRP',
    sendTxActiveNewAccount: '该账户未激活，若需要激活该账户请至少转20 XRP',
    XRPNotActive: '未激活',
    confirmSend: '确认发送',
    clear: '清除',
    recipientRequired: '收款人地址必填',
    recipientInvalid: '收款人地址无效',
    amountInvalid: '请输入正确的金额',
    amountInvalid_fractionalamount: '该币种只可交易整数金额',
    balanceNotEnough: '转账金额加矿工费须小于余额',
    usdtBalanceNotEnough: '转账金额须小于余额',
    btcBalanceNotEnough: 'BTC余额不足，无法支付最低转账金额+矿工费',
    usdtFeeMention: 'USDT基于BTC，转账需要支付BTC矿工费',
    usdtAmountMention: 'USDT基于BTC，转账需要消耗最低的BTC转账金额(dust)',
    ethNotEnough: 'ETH余额太少，无法满足交易手续费',
    qrScanTitle: '请将二维码对准摄像头并置于红框内',
    readQRError: '读取二维码失败，请检查并重试',
    pleaseConfirmOnKey: '请在设备上核对交易明细，并按‘OK’键以签名交易',
    notAllInitialized: '有星钥未完成初始化，请检查并重启软件以重新连接',
    gasInvalid: '请输入正确的gas',
    gasPriceInvalid: '请输入正确的gas price',
    feeInvalid: '请输入正确的矿工费',
    usdtFeeInvalid: 'BTC余额不足以支持手续费',
    otherFeeInvalid: '余额不足以支持手续费',
    nonceInvalid: '请输入有效的Nonce',
    notMatchMHint: '插入的星钥数不满足初始设定，请检查并重启软件以重新连接',
    updatingCOS: '正在升级设备固件……',
    updateCosStopTips: '请重新拔插设备',
    updatingCOSHint:
      '请在设备上按“OK”键以升级固件。升级完成前请勿中途退出，软件将在升级后重启。',
    checkUpdate: '检查更新',
    operationCancelled: '操作已取消',
    changepin: '修改 PIN',
    register: '注册账户',
    registerAccount: '用户名',
    registerLoading: '加载中',
    registerCaptcha: '验证码',
    registerSubmit: '提交',
    registersuccess: '注册成功',
    registerErr403: '验证码错误',
    registerErr507: '用户名已被使用',
    registerErr429: '注册限制',
    registerErrEOS10002: '该设备已注册过EOS账户',
    registerErrEOS10003: '邀请码不存在',
    registerErrEOS10004: '用户名已被注册',
    registerErrEOS10005: '用户名包含无效字符',
    registerErrEOS10006: '用户名长度只能是12位',
    registerErrEOS10007: '请求参数错误',
    registerErrEOS10008: '无效的公钥',
    registerErrEOS10012: '无效参数',
    registerErrEOS10014: '验签失败',
    registerErrEOS10020: '用户名与公钥不匹配',
    registerErrEOS20001: '账户余额不足',
    registerErrEOS20002: '账户创建失效',
    registerErrOther: '注册失败',
    registerNotCheapNmae: '用户名包含至少一个横杠、数字或者不含元音字母',
    registerAccountErrLetter: '用户名的每个片段须以字母开头',
    registerAccountErrStartWithLetter: '用户名应该以小写字母开头',
    registerAccountErrLonger: '用户名过短',
    registerAccountErrShorter: '用户名过长',
    registerAccountErrOnlyldd: '用户名只能由字母，数字，‘.’和‘-’组成',
    registerAccountErrEndWithLetter: '用户名的每个片段只能以字母或数字结尾',
    registerAccountErrLowwer: '用户名字母只能为小写',
    registerAccountErrEOSInvitationCode: '无效的邀请码',
    appDefaultError: '发生错误 (错误码：XXX)，请稍后再试或联系技术支持',
    info: '提示',
    download: '下载',
    OK: '确定',
    cancel: '取消',
    updateFinish: '新版客户端下载完成',
    updateCOSTitle: '有新版固件可下载',
    updateAppTitle: '软件更新',
    updateCosTitle: '固件更新',
    ETHDerivePath: 'ETH衍生路径',
    FiatType: '法币单位',
    ETHDerivePathMention: '兼容Trezor、Metamask、Exodus、Jaxx等',
    ETHDerivePathDefaultMention: '默认，兼容Ledger',
    updateCOSMessage: '强烈建议使固件保持最新以获得更好的安全性',
    updateAppMessage: '请确认下载此版本: ',
    restartNow: '现在重启',
    updateNow: '立即更新',
    restartLater: '下次再说',
    COSUpdateMessage: '固件更新已就绪',
    ETHDerivePathChange: '衍生路径已修改，即将重新连接',
    SoftwareUpdateMessage: '软件更新已就绪',
    updateCOSRestartTitle: '固件下载已完成',
    updateCOSRestartMessage: '固件更新将在软件重启后开始进行',
    updateAPPRestartMessage: '客户端更新将在重启后开始进行',
    updateAPPFail: '更新失败',
    errorPinLocked: 'PIN已锁定',
    errorPinConfirmFail: '两次输入的PIN不一致',
    errorPinVerifyFail: 'PIN验证失败，可能输入了错误的PIN',
    errorDeviceStatus: '设备状态有误，请先切换到正常状态',
    viewHistory: '查看交易记录',
    refresh: '刷新余额',
    unavailable: '暂不可用',
    showQRCode: '显示二维码',
    registerAccountErrZh: '用户名不可包含中文',
    registerAccountErrEOSld: '用户名只能由 ‘1-5’ 和 ‘a-z’ 组成且长度必须12位',
    downloadSuccessful: '下载成功！',
    downloading: '正在下载...',
    newSize: '新版本大小 ',
    willDownload: '即将开始下载...',
    coinAddressError: '未读取到币种地址',
    memoLenError: 'memo最大长度为140',
    memoInputError: 'memo目前仅支持英文、数字、标点符号',
    tagUnvalid: 'Tag 必须是 0-4294967295 的数字',
    accountNotActived: 'Ripple需要一个最小余额 20 XRP',
    registerPublicKey: '公钥',
    pkgSignFailMessage: '更新文件校验错误',
    pkgSignFailDetail:
      '电脑或网络环境可能存在安全风险，更新文件被篡改，请检查后重试',
  },
  en: {
    appName: 'WOOKONG Wallet',
    language: 'Language',
    closeModal: 'Close',
    closeMemoModal: 'Cancel',
    memoSubmit: 'Done',
    copyAddress: 'Copy Address',
    saveImg: 'SAVE QR',
    copyPbkey: 'Copy public key',
    settings: 'Settings',
    reload: 'Reconnect…',
    unlockToast: 'Please make sure the hardware unlocked.',
    reconnectToast: 'Please remove and reconnect the hardware',
    modifyPINError: 'Failed to modify the PIN. Please check and try again',
    modifyPINSuccess: 'The PIN has been modified, app will restart in seconds',
    sendTxSuccess: 'Transaction sent: {0}. Click to view details.',
    sendTxError: 'Failed to send the transaction. Please check and try again.',
    confirmLaunchText: 'Please make sure the <b>hardware</b> has been inserted',
    confirmLaunchHint:
      'Tips: Standalone mode available if only one Astrokey inserted',
    astroKey: 'Astrokey',
    confirmLaunchBtn: 'Confirm',
    connectError: 'Connected Error',
    connectHintNotSameGroup:
      'The Astrokeys inserted may be not in the same group. Please check or contact the technical support.',
    connectHintNotInited:
      'Some Astrokey may be not initialized. Please check or contact the technical support',
    connectSuccess: 'Connected',
    connectHintTooMuchDev:
      'Too many devices, please connect only one device each time',
    fetchingAddresses: 'Fetching Currency Addresses',
    fetchingHint:
      "Please click the 'OK' button on the hardware to allow to read the addresses",
    readyToInit: 'Ready to initialize…',
    readyHint: 'You could use <b>WOOKONG Hardware Wallet</b> once initialized',
    connecting: 'Connecting…',
    connectingHint: 'Notice: please unlock the hardware',
    connectingHintNotReady:
      'The hardware is not ready, please make sure its screen is showing WOOKONG',
    retry: 'Retry',
    next: 'Next',
    createNewWallet: 'Create New Wallet',
    importmemo: 'Import Mnemonics',
    importmemolabel: 'Input Mnemonics',
    importmemoTips:
      "Please unlock the hardware and click the 'IMPORT' button to input mnemonics",
    importmemoIng: 'Now importing',
    importmemoIngTips: 'Please follow the guide on the hardware',
    importmemoSubmit: 'Import',
    importmemoError: 'Error!',
    importmemoErrorTips: 'Please check the mnemonics and try again',
    importmemoSuccess: 'Importing completed',
    noKeys: 'No hardware found or wrong hardware connected',
    tooManyKeys: 'Too many Astrokeys found',
    initError: 'Initialized Error',
    retryHint: 'Please check or contact the technical support',
    initSuccess: 'Initialized!',
    initSuccessHint:
      'Notice：Please unlock the hardware, then allow to read the addresses.',
    initing: 'Initializing…',
    initingHint:
      'Please wait until the progress finished and write down the recovery phrase carefully.',
    checkAndRetry: 'Oops! Please check and try again',
    enter: 'Enter',
    selectThreshold: 'Please select the threshold',
    minThresholdHint:
      'Set the number of Astrokeys (>= 2) used to make a signature',
    keymanageMode: 'Astrokey Manager',
    modifyPINOption: 'Modify PIN',
    modifyPINOptionHint:
      'Please follow the guide on the hardware to modify the PIN',
    FingerprintOption: 'Fingerprint Manager',
    FingerprintOptionHint: 'Fingerprint list, add or delete fingerprint',
    DiskOption: 'Disk Manager',
    DiskOptionHint: 'Open disk by PIN or format disk',
    format: 'Format Wallet',
    formatError: 'Format error!',
    formatSuccess: 'Success! app will restart in seconds',
    formatHint:
      'All the information will be cleared after formatting. Please make sure the property is safe before formating.',
    tabItemOverview: 'Home',
    tabItemSend: 'Send',
    tabItemProfile:'Profile',
    address: 'Address',
    copiedToClipboard: 'Address has been copied to clipboard.',
    checkAddressInfo: 'Address Details',
    eosRegisterConfirmKey:
      'Please compare the public key displayed on the hardware screen to ensure the same',
    confirmAddressOnKey:
      'Compare the address displayed on the hardware screen to make sure it matches the one on the bullet box. Press “OK” to confirm the address to use the copy function and display the QR code. Press "C" to cancel and close the popover',
    confirmRegAddressOnKey:
      'Compare the addresses displayed on the hardware screen to make sure they are consistent. Click "OK" to confirm the submission',
    confirmCopyAddressOnKey:
      'Please compare the public key displayed on the hardware screen. If it is consistent, please click "OK" to confirm and use the public key to register the EOS account by yourself. Otherwise, press "C" to cancel.',
    waitConfirm: 'Waiting for confirmation',
    totalAssets: 'Total Assets',
    balance: 'Balance',
    fee: 'Fee',
    fullBalance: 'Full balance',
    advanced: 'Advanced',
    alreadyUpdateMention: 'Already up-to-date',
    updateMention: 'New version found!',
    updateSpanSW: 'SW',
    updateSpanFW: 'FW',
    btcFeePolicyFasterLabel: 'Fee Policy: Urgent',
    btcFeePolicyFasterText: 'Urgent',
    btcFeePolicyFastLabel: 'Fee Policy: Priority',
    btcFeePolicyFastText: 'Priority',
    btcFeePolicyNormalLabel: 'Fee Policy: Normal',
    btcFeePolicyNormalText: 'Normal',
    btcFeePolicyEconomicalLabel: 'Fee Policy: Economy',
    btcFeePolicyEconomicalText: 'Economy',
    btcFeePolicyCheapLabel: 'Fee Policy: Super Economy',
    btcFeePolicyCheapText: 'Super Economy',
    btcFeePolicyPoorLabel: 'Fee Policy: Extremely Economy',
    btcFeePolicyPoorText: 'Extremely Economy',
    ethFeePolicyDefaultLabel: 'Fee Policy: Default',
    ethFeePolicyDefaultText: 'Default',
    ethFeePolicyCustomLabel: 'Fee Policy: Advanced',
    ethFeePolicyCustomText: 'Advanced',
    estimate: 'Estimate',
    minute: 'minutes',
    coinType: 'Currency',
    latestVersion: 'Your software is up to date',
    latestTotal: 'The software and firmware are up to date',
    setttingSW: 'SW Ver:',
    setttingFW: 'FW Ver:',
    latestCOSVersion: 'The firmware is up to date',
    recipientAddress: 'Recipient',
    recipientHint: 'Please input the recipient address',
    memo: 'Memo',
    memoHint: '(Optional)',
    sendAmount: 'Amount',
    exceedBalanceHint: 'Balance not enough to cover the amount and fee',
    xrpBalanceNotEnough:
      "A minimum of 20 XRP shall be retained after deducting the transfer amount + miner's fee",
    sendTxActiveNewAccount:
      'This account is not activated. If you need to activate this account, please transfer to at least 20 XRP',
    XRPNotActive: 'Not actived',
    confirmSend: 'Send',
    clear: 'Clear',
    recipientRequired: 'Required',
    recipientInvalid: 'Invalid address',
    amountInvalid: 'Invalid amount',
    amountInvalid_fractionalamount: 'Integral number only',
    balanceNotEnough: 'Balance is not enough to cover amount + fee',
    usdtBalanceNotEnough: 'Balance is not enough to cover amount',
    btcBalanceNotEnough:
      'BTC balance is insufficient to pay the minimum transfer amount + miner fee',
    usdtFeeMention:
      'USDT is based on BTC, and the transfer needs to pay BTC miners fees',
    usdtAmountMention:
      'USDT is based on BTC, and transfer needs to consume the lowest amount of BTC transfer (dust)',
    ethNotEnough: 'ETH is not enough to cover the transaction fee',
    qrScanTitle: 'Please align the QR code with the camera',
    readQRError: 'Failed to read the QR code. Please check and try again',
    pleaseConfirmOnKey:
      'Please check the transaction details on the hardware, then click the "OK" button to confirm the transation',
    notAllInitialized:
      'There are some Astrokey(s) not initialized. Please make sure that all Astrokeys initialized and then restart app to try again.',
    gasInvalid: 'Invalid gas',
    gasPriceInvalid: 'Invalid gas price',
    feeInvalid: 'Invalid fee',
    usdtFeeInvalid: 'BTC balance is insufficient to support the handling fee',
    otherFeeInvalid: 'Balance is insufficient to support the handling fee',
    nonceInvalid: 'Invalid nonce',
    notMatchMHint:
      'The number of inputed Astrokeys does not match the setup condition. Please do check then restart the app to reconnect.',
    updatingCOS: 'Updating Astrokey Firmware…',
    updateCosStopTips: 'Please remove and reconnect the hardware',
    updatingCOSHint:
      "Please click the 'OK' button on the hardware to finish the process. App will restart later.",
    checkUpdate: 'Check Update',
    operationCancelled: 'Operation cancelled',
    changepin: 'CHANGE PIN',
    register: 'Register',
    registerAccount: 'Account Name',
    registerLoading: 'Loading...',
    registerCaptcha: 'Captcha',
    registerSubmit: 'Submit',
    registersuccess: 'Success',
    registerErr403: 'Wrong Captcha',
    registerErr507: 'This account name has been used',
    registerErr429: 'Limited Device',
    registerErrEOS10002: 'Invitation code is used',
    registerErrEOS10003: 'Invitation code does not exist',
    registerErrEOS10004: 'This account name has been used',
    registerErrEOS10005: 'Account name contains invalid character(s)',
    registerErrEOS10006:
      'Account name should have a fixed length of 12 characters',
    registerErrEOS10007: 'Wrong request parameters',
    registerErrEOS10008: 'Invalid public key',
    registerErrEOS10012: 'Invalid parameter',
    registerErrEOS10014: 'Verification failure',
    registerErrEOS10020: 'Account and public key does not match',
    registerErrEOS20001: 'Insufficient faucet balance',
    registerErrEOS20002: 'Register invalid',
    registerErrOther: 'Error',
    registerNotCheapNmae:
      'Please enter a regular name containing least one hyphen-minus, a number or no vowels.',
    registerAccountErrLetter: 'Each account segment should start with a letter',
    registerAccountErrStartWithLetter:
      'Account name should start with a letter',
    registerAccountErrLonger: 'Account name should be longer',
    registerAccountErrShorter: 'Account name should be shorter',
    registerAccountErrOnlyldd:
      'Account name should have only letters, digits, or hyphens',
    registerAccountErrEndWithLetter:
      'Account name should end with a letter or digit',
    registerAccountErrLowwer: 'All letters are lowercase',
    info: 'Info',
    download: 'Download',
    OK: 'OK',
    cancel: 'Cancel',
    updateFinish: 'Updates downloaded',
    updateCOSTitle: 'New firmware found',
    updateCOSMessage:
      'It is highly recommended to keep firmware up-to-date for better security',
    updateAppTitle: 'Software update',
    updateCosTitle: 'Firmware update',
    ETHDerivePath: 'ETH Derive Path',
    FiatType: 'Legal Currency Unit',
    ETHDerivePathMention: 'Compatible with Trezor, Metamask, Exodus, Jaxx, etc',
    ETHDerivePathDefaultMention: 'By default, compatible with Ledger',
    updateAppMessage: 'Please confirm to download this version: ',
    restartNow: 'Restart Now',
    updateNow: 'Update Now',
    restartLater: 'Later',
    COSUpdateMessage: 'Firmware update is ready',
    ETHDerivePathChange:
      'The ETH derived path has been modified and is about to reconnect',
    SoftwareUpdateMessage: 'Software update is ready',
    updateCOSRestartTitle: 'Firmware downloaded',
    updateCOSRestartMessage: 'Firmware will be updated after restart',
    updateAPPRestartMessage: 'Software will be updated after restart',
    updateAPPFail: 'Updates downloaded fail',
    errorPinLocked: 'PIN is locked',
    errorPinConfirmFail: 'Entered PINs differ',
    errorPinVerifyFail: 'Verify PIN failed, the PIN you input maybe wrong',
    errorDeviceStatus:
      'Invalid device status, please switch to normal status first',
    viewHistory: 'View transactions history',
    refresh: 'Update balance',
    unavailable: 'Not available',
    showQRCode: 'Show QR Code',
    registerAccountErrZh: 'Account name should not contain Chinese',
    registerAccountErrEOSld:
      "Account name can only consist of '1-5' and 'a-z' and must be 12 digits in length",
    registerAccountErrEOSInvitationCode: 'Invalid invitation code',
    appDefaultError:
      'An error occurred (error code: XXX), please try again later or contact technical support',
    downloadSuccessful: 'Download successful！',
    downloading: 'Downloading...',
    newSize: 'The Size of new version is ',
    willDownload: 'Start downloading now... ',
    coinAddressError: 'Can not read coin address',
    memoLenError: 'Memo has a maximum length of 140',
    memoInputError: 'Memo should have only letters，numbers，punctuation',
    tagUnvalid: 'Tag must be a number that has to be 0-4294967295',
    accountNotActived: 'Ripple need a minimum balance: 20 XRP',
    registerPublicKey: 'Public KEY',
    pkgSignFailMessage: 'Update file validation error',
    pkgSignFailDetail:
      'There may be security risks in the computer or network environment. The updated file has been tampered with. Please check it and try again',
  },
});

export default strings;
